### ISSUE TITLE
Golang: missing parameter hint on variable function call.

### ISSUE THREAD

**Issue by x-user** [RobertOstermann/vscode-inline-parameters#10]
![Screenshot_20220527_180647](https://user-images.githubusercontent.com/5990152/170727895-f62c9388-a5bc-46a7-a1bb-22255bb9533b.png)

GO version: `1.18`
Parser output for `line 19`:
```
expression call: walkValue | expression line: 19 | expression character: 13 | argument start line: 19 | argument start character: 14 | argument end line: 19 | argument end character: 26
NEW EXPRESSION
expression call: &{val Field} | expression line: 19 | expression character: 23 | argument start line: 19 | argument start character: 24 | argument end line: 19 | argument end character: 25
NEW EXPRESSION
```

**Comment by RobertOstermann** [comment]
I have publish version 1.2.4 with some improvements to the parameter hints. This should fix the problem you are seeing where anonymous functions were not receiving parameter hints.

**Comment by x-user** [comment]
Yes it works now. Thank you.
