### ISSUE TITLE
The last one is outside the bracket (golang）

### ISSUE THREAD

**Issue by cyrus123456** [RobertOstermann/vscode-inline-parameters#12]
The last one is outside the bracket
![image](https://user-images.githubusercontent.com/73327722/175799141-3488fdfb-2b05-4c70-82a6-38a816f6c798.png)

**Comment by RobertOstermann** [comment]
@cyrus123456 Is this still occurring or was it a one-time problem? Sometimes the parameters get placed in the wrong places, especially for large files or if you are still typing. If that is the case, I am not sure how much I could do to fix it, but if this is something that is consistently occurring then I will look into it further. It could be a problem of me not specifying the encoding as I have to write the contents of the file to a temporary location to use an AST to find the locations to place the parameters. I only have to write that temporary file for GO and Python, so do you know if this is also a problem for other languages, such as Java or PHP?

**Comment by cyrus123456** [comment]
> @cyrus123456 Is this still occurring or was it a one-time problem? Sometimes the parameters get placed in the wrong places, especially for large files or if you are still typing. If that is the case, I am not sure how much I could do to fix it, but if this is something that is consistently occurring then I will look into it further. It could be a problem of me not specifying the encoding as I have to write the contents of the file to a temporary location to use an AST to find the locations to place the parameters. I only have to write that temporary file for GO and Python, so do you know if this is also a problem for other languages, such as Java or PHP?

Sorry, I just developed it with golang.FMT or log, which often happens

**Comment by RobertOstermann** [comment]
Ok, I will look into this further, but it might take me a week or two before I have the free time to do so.

**Comment by RobertOstermann** [comment]
@cyrus123456 Ok, I think I have found a fix for this issue. Please upgrade the extension to version 1.2.5 and let me know if that fixes the problem.

**Comment by RobertOstermann** [comment]
Closing as there has been no response
