### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rochmanramadhann** [RobertOstermann/vscode-inline-parameters#13]
- Issue Type: `Performance`
- Extension Name: `inline-parameters-extended`
- Extension Version: `1.2.5`
- OS Version: `Darwin arm64 21.6.0`
- VS Code version: `1.70.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/p5/j_mfhhbn3dzf5vbm73pqcmmw0000gn/T/RobertOstermann.inline-parameters-extended-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RobertOstermann** [comment]
Could you attach the file mentioned in the issue? Also. when are you seeing these performance issues and for what file type (PHP, Python, etc.) are you seeing the problems with?

**Comment by RobertOstermann** [comment]
Closing as no response was given
