### ISSUE TITLE
vscodium support

### ISSUE THREAD

**Issue by zakaria-chahboun** [RobertOstermann/vscode-inline-parameters#14]
Hi! First of all thank you for this useful extension.

I use `vscodium` which is a clone of vscode, we can't use your extension right now because you have to published it to  [open-vsx](https://open-vsx.org/) too.

Thanks!

**Comment by RobertOstermann** [comment]
@zakaria-chahboun Let me know if this works for you.
https://open-vsx.org/extension/RobertOstermann/inline-parameters-extended

**Comment by zakaria-chahboun** [comment]
@RobertOstermann Yes. Thanks
