### ISSUE TITLE
Are any way to remove background on the inline name parameters ?

### ISSUE THREAD

**Issue by pirex360** [RobertOstermann/vscode-inline-parameters#16]
How to remove the background of the inline parameters ? and put italics format for example ?

**Comment by RobertOstermann** [comment]
@pirex360

You can change the background color of the inline parameter in your settings.json. Here is an example of changing it for the **Default Dark+** theme.

```json
{
"workbench.colorCustomizations": {
    "[Default Dark+]": {
      "editorInlayHint.background": "#ff0000"
    }
  },
}
```

You can change the font style in your settings.json as well. Here is an example.
```json
{
  "editor.inlayHints.fontFamily": "FONT FAMILY"
}
```

**Comment by pirex360** [comment]
Thanks, it's more an aspect of VsCode customization, but if you expose all the props in the documentation maybe you are free for newbie questions :)

Awesome extension, thanks for all the work.
