### ISSUE TITLE
Python: single letter parameters aren't handled

### ISSUE THREAD

**Issue by nikola-damjanovic-wd** [RobertOstermann/vscode-inline-parameters#18]
The `+` should be a `*` here to also capture single letter parameters.
https://github.com/RobertOstermann/vscode-inline-parameters/blob/b79b30f127e4b23cb32414d253772657fa8e5074/src/python/pythonHelper.ts#L161

I don't know if this warrants it's own PR. So, when a new PR comes around you can bundle this small fix with it.

**Comment by RobertOstermann** [comment]
Should be fixed in v1.2.9

**Comment by nikola-damjanovic-wd** [comment]
Just checked, and I can confirm this is now fixed.
