### ISSUE TITLE
Golang support plan?

### ISSUE THREAD

**Issue by bubbleboy11** [RobertOstermann/vscode-inline-parameters#2]

**Comment by RobertOstermann** [comment]
@bubbleboy11 I have published version 1.0.8 that has Golang support included. You will need the ability to run the **go** command directly from a terminal (basically in your path environment variables) as I had to use Golang to parse the files. This is my first time doing anything with Golang so if you see any problems create another issue and I will attempt to fix it.

If you are enjoying the extension, please leave a review on the [vscode marketplace](https://marketplace.visualstudio.com/items?itemName=RobertOstermann.inline-parameters-extended).

**Comment by bubbleboy11** [comment]
Thank you, I have reviewed wtih five star.
