### ISSUE TITLE
[feat] Add JavaScript/TypeScript Support

### ISSUE THREAD

**Issue by moritztim** [RobertOstermann/vscode-inline-parameters#20]
I'd love to see inline params for js & ts

**Comment by RobertOstermann** [comment]
@moritz-t-w 
I do not plan on adding support for JS/TS. I would recommend using the built-in inlay hint functionality provided by VSCode, which is better than anything I could provide. These are the settings that must be enabled in your settings.json file to mirror the functionality I have provided in this extension.
```json
"editor.inlayHints.enabled": true,
"javascript.inlayHints.parameterNames.enabled": "all",
"typescript.inlayHints.parameterNames.enabled": "all"
```
There are several additional settings you can enable if you want inlay hints provided in places other than just the parameter names. Here is some documentation for the inlay hint support provided by VSCode.
https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_60.md#inlay-hints-for-javascript-and-typescript

**Comment by moritztim** [comment]
oh that was quick, thank you I didn't know about this!
