### ISSUE TITLE
[Feature Request] Configuration for function names to ignore inline hinting

### ISSUE THREAD

**Issue by iAmNikola** [RobertOstermann/vscode-inline-parameters#22]
Hi again! :)

I find this extension extremely helpful for new code and packages that I'm using, but it still has room for improvement. At least on the Python side, since that's what I'm using it for.

### Describe the Feature Request

Many Python's built-in functions' parameters are unnecessary to inlay hint and introduce unnecessary clutter most of the time. Also, use of keyword arguments in many Python's built-in functions calls just doesn't work because many built-in functions are C functions bound to Python.

Because of that, I propose having a configuration argument that would ignore built-ins, if that is even feasible.
If not that, the second best thing would be to allow configuring an ignore list of function names that will never be inlay hinted.

I find this feature to be neat and it would also expand on the customizability of the extension.

### Describe Preferred Solution

If built-in ignoring is possible the user would need to set e.g. `"inline-parameters.python.ignoreBuiltIns": true` in VS Code's `settings.json`.

### Describe Alternatives

Seeing that the above is probably far-fetched, I propose giving users an option to configure a list of functions they don't want to inlay hint instead.
The user would have to define e.g.  `"inline-parameters.python.functionsToIgnore": ["print", "len", "sort", ...]` in `settings.json`.

### Related Code

I haven't developed any extension so I don't have any experience in the process of building and testing the changes of a VS Code extension.

I have no clue how the main proposal would be implemented, but I have an idea of what changes need to be made to implement the alternative.

The following suggestions are for Python, but it probably applies to all of them, implementation-wise.

The new configuration option with an empty list as the default value should be added here:
https://github.com/RobertOstermann/vscode-inline-parameters/blob/fb2e29fbf586b61d3c8c2915dc675d52f05075af/package.json#L152-L157

And here as well:
https://github.com/RobertOstermann/vscode-inline-parameters/blob/fb2e29fbf586b61d3c8c2915dc675d52f05075af/src/python/pythonConfiguration.ts#L37-L40

Finally we just need to modify the condition to also check the ignore list:
https://github.com/RobertOstermann/vscode-inline-parameters/blob/fb2e29fbf586b61d3c8c2915dc675d52f05075af/src/python/pythonDriver.ts#L31

The modified condition would be something along the lines of:
```ts
if (
    parameters[index] === undefined || 
    parameters[index].name === undefined || 
    PythonConfiguration.functionsToIgnore().includes(parameters[index].name)
) {
    continue;
}
```

Thanks for reading this long write-up :) . I will be very grateful if this can be implemented in any way, shape or form.
I'll gladly help/assist if I can be of any use :D

**Comment by RobertOstermann** [comment]
@iAmNikola Thanks for the well-written issue. I have pushed update v1.3.1 which hopefully provides the feature you are looking for. I have not tested this much, so not sure how well the solution I provided covers the built in functions. I updated the `main.py` file to allow an additional argument which determines if built in functions should be included. If not, it excludes those functions using the `import builtins` as a list of built in functions.

Let me know if this solution is good enough. If not, I could update to use the solution you provided, or include your solution as an additional setting.

**Comment by iAmNikola** [comment]
Hi @RobertOstermann, thanks for the quick response!

The implementation works as expected in various scenarios, it doesn't hint built-ins when the option is enabled. However, I may have phrased my feature request a bit poorly.

When I said "built-ins" i also mean standard library functions/classes. No clue why the words "standard library" haven't occured to me while I was writing the initial feature request... That's the reason why I said i don't think its easily doable. My apologies if I caused any confusion.

The current implementation does improve things a bit by ignoring basic python functions. It still "misses" all primitive instances functions e.g. `.append()`, `.setdefault()`, `.format()`, etc.
For my work/projects, the current implementation feels incomplete.

I've been researching a possible solution on the internet for a some time, but I haven't found anything useful so far.
Currently, I would benefit much more if I just had the option to define a list of names to ignore.

Also on a, somewhat, related note 😄 Availability to enable/disable certain features, like turning off/on the inlay hinting altogether with VS Code command (Ctrl+Shift+P) could also be a nice improvement if it's easy to implement.

Thanks you for maintining this project. Godspeed

P.S. Would be much appreciated if you could push the current and future changes to GitHub as well 🙏

**Comment by RobertOstermann** [comment]
I believe the changes are pushed to GitHub. Though I just push to the main branch and don't do PRs often. I should have some time this weekend to implement your suggestion.

**Comment by iAmNikola** [comment]
Can you please double-check. This is what I'm seeing on my end:
![image](https://github.com/RobertOstermann/vscode-inline-parameters/assets/58849671/89d5fa38-fc03-4c21-8239-c0d5c19b17d3)

Thanks!

**Comment by RobertOstermann** [comment]
I stand corrected, must not have pushed the changes. Should be fixed now

**Comment by iAmNikola** [comment]
Thanks a lot! :)

**Comment by RobertOstermann** [comment]
@iAmNikola v1.3.2 should have the updates for ignoring custom function in Python with the `inline-parameters.python.ignoreFunctions` configuration setup.

Not sure I will get to the "Availability to enable/disable certain features, like turning off/on the inlay hinting altogether" feature, seems more live an overall VSCode feature, though enabling/disabling by language with command might make sense. This is lower priority though so might not get to it.

**Comment by iAmNikola** [comment]
@RobertOstermann I've been playing with the feature for a couple of days now and all I can say is that I really enjoy having the flexibility. The current implementation is great and I think we can close this feature request as **completed** 🎉. I owe you a coffee for this one 😄 

The command thing is just a nice thing to have, but I have no clue if its tiresome to implement haha

Much thanks for your time and effort! I appreciate it a lot 

P.S. Please push the changes to github as well 🙏

**Comment by RobertOstermann** [comment]
Oops, keep forgetting to push my changes. They should be up now.
