### ISSUE TITLE
`[1.3.2] - 2024-04-13` does not work for go

### ISSUE THREAD

**Issue by FreePhoenix888** [RobertOstermann/vscode-inline-parameters#23]
There are no inline parameters like in JetBrains IDE's
![image](https://github.com/user-attachments/assets/c2525558-f09c-478a-9b6d-b09f7ec6124d)
![image](https://github.com/user-attachments/assets/1b88a2d0-fe8d-4b2e-ab9e-1f4c66c6a94e)
![image](https://github.com/user-attachments/assets/10eca656-fc81-44d0-bfdf-114171581ff6)

**Comment by FreePhoenix888** [comment]
@RobertOstermann

**Comment by RobertOstermann** [comment]
@FreePhoenix888 Not sure why this wouldn't be working. I rarely use the extension for golang. I uploaded v1.3.3, which might fix your issue, but I doubt it. Could you check the output channel and try running the golang command, see what error you get? Here is an example of the command it should show you.

![image](https://github.com/user-attachments/assets/441205a6-1b2f-4581-abb6-285c3f2e18bf)

**Comment by FreePhoenix888** [comment]
@RobertOstermann Sorry for disturbing you. I have checked other files and it seems inline parameters work except one file. If I will find out that this is a bug of the extension I will open another issue. Thank you for your time! And thank you for this extension!

**Comment by RobertOstermann** [comment]
@FreePhoenix888 Try setting `inline-parameters.go.suppressWhenArgumentMatchesName` to false. I think that is the issue.
