### ISSUE TITLE
Parameter suggestions missing when variable name is the same as parameter name for Go

### ISSUE THREAD

**Issue by qinxuan2006** [RobertOstermann/vscode-inline-parameters#25]
Thank you very much for supporting Go with this plugin! However, I found an issue: it works well when parameter names and variable names are different, but when the variable name and parameter name are the same, there is no parameter suggestion, as shown in the figure below.
<img width="574" alt="image" src="https://github.com/user-attachments/assets/af12aa7e-0ed4-4bae-95b8-ce18b1625ef6">
<img width="717" alt="image" src="https://github.com/user-attachments/assets/b606aefe-bbf8-4061-b0bb-0fd42a3293ad">
PS: I think the issue described in #23  is also the same problem. The parameter t and the passed variable t have the same name, so there is no suggestion.

**Comment by RobertOstermann** [comment]
Have you tried setting `inline-parameters.go.suppressWhenArgumentMatchesName` to false?

**Comment by qinxuan2006** [comment]
> Have you tried setting `inline-parameters.go.suppressWhenArgumentMatchesName` to false?

Wow，it works. Thank you very much
