### ISSUE TITLE
JS/TS support 

### ISSUE THREAD

**Issue by BobbyJonas** [RobertOstermann/vscode-inline-parameters#6]
my fellow,
when is js/ts support available?

it'll be a great experience to use this extension for both fe/be development.

**Comment by RobertOstermann** [comment]
I do not plan on adding support for JS/TS. I would recommend using the built-in inlay hint functionality provided by VSCode, which is better than anything I could provide. These are the settings that must be enabled in your _settings.json_ file to mirror the functionality I have provided in this extension.

```json
"editor.inlayHints.enabled": true,
"javascript.inlayHints.parameterNames.enabled": "all",
"typescript.inlayHints.parameterNames.enabled": "all"
```

There are several additional settings you can enable if you want inlay hints provided in places other than just the parameter names. Here is some documentation for the inlay hint support provided by VSCode.
[https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_60.md#inlay-hints-for-javascript-and-typescript](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_60.md#inlay-hints-for-javascript-and-typescript)

**Comment by BobbyJonas** [comment]
that's alright, thanks a lot btw!
