### ISSUE TITLE
How to modify the background color

### ISSUE THREAD

**Issue by cyrus123456** [RobertOstermann/vscode-inline-parameters#8]
![image](https://user-images.githubusercontent.com/73327722/169635707-50f29e86-173c-4b16-9ef6-e60d0875e40d.png)

**Comment by cyrus123456** [comment]
Yellow is too ugly, I want to change to transparent

**Comment by RobertOstermann** [comment]
You can change the background color by changing the `workbench.colorCustomizations` in your `settings.json`. Here is an example of the possible values that could be changed. You will probably only need to add the `editorInlayHint.background` and `editorInlayHint.foreground` values. You will have to change the color to the color you want as this example just uses red as the color.

```json
"workbench.colorCustomizations": {
      "editorInlayHint.background": "#ff0000",
      "editorInlayHint.foreground": "#ff0000",
      "editorInlayHint.parameterBackground": "#ff0000",
      "editorInlayHint.parameterForeground": "#ff0000",
      "editorInlayHint.typeBackground": "#ff0000",
      "editorInlayHint.typeForeground": "#ff0000",
}
```
