### ISSUE TITLE
Java: parameter hints duplication

### ISSUE THREAD

**Issue by x-user** [RobertOstermann/vscode-inline-parameters#9]
When builtin inlay hints for java enabled the hints appears twice even when inline-parameters.java.enabled set to false.

OS: Windows 10
vscode version: 1.67.2
extension version: 1.2.1
settings:
`{
  "inline-parameters.java.enabled": false,
  "java.inlayHints.parameterNames.enabled": "all"
}`

![Screenshot 2022-05-27 040336](https://user-images.githubusercontent.com/5990152/170608085-b653058f-05db-4de3-aee8-1107a7e049ea.png)

**Comment by RobertOstermann** [comment]
@x-user Thanks for providing that information. Looks like I had a bug that made it impossible to disable my extension for individual languages, which is why you are seeing the inlay hints appear twice. I have pushed a fix in version 1.2.2, which should solve your problem.

**Comment by x-user** [comment]
It works like a charm. Thank you.
